### PR TITLE
upgrade sveltekit

### PR DESCRIPTION
**Pull request by akisblack**

### CODE REVIEW

**Review by Odyssey346 — APPROVED** [review]
AAAAAAAAAAAAAAA
but yeah

**Comment by Midou36O** [comment]
Question: why upgrade again?

**Comment by akisblack** [comment]
because staying on an old version can be a security risk and also because there are more upcoming breaking changes we'll have to migrate to

**Comment by Midou36O** [comment]
Are you for the upgrade or against the upgrade???

**Comment by akisblack** [comment]
i certainly do not like the changes but i can tolerate it

**Comment by Midou36O** [comment]
I don't like the change, i'll see if i can make to different branches on the github repo, put the main branch on the updated svelte and create a different branch that backport the svelte functions. The website will be built on the new svelte.

**Pull request closed without merging**
