### PR TITLE
docker

### PR DESCRIPTION
**Pull request by akisblack**
article i took the code from: https://sveltesociety.dev/recipes/publishing-and-deploying/dockerize-a-svelte-app
**docs:**
- build image: `docker build . -t website`
- run image: `docker run --rm --name=website -p 80:80 website` 

ps: i havent tested this enough

### CODE REVIEW

**Comment by Odyssey346** [comment]
test it more

**Comment by Midou36O** [comment]
fyi this will be pushed to the projectsegfault account too

**Comment by Midou36O** [comment]
Also 
image

**Comment by Midou36O** [comment]
Did you test it?

**Comment by akisblack** [comment]
yes, it works. announcements arent being shown because there are issues with cors odyssey gotta fix (these issues also happen on the prod site so it isnt an issue specific to docker)

**Comment by Midou36O** [comment]
I'll test it first
Gimme a few minutes

**Comment by Midou36O** [comment]
> there are issues with cors odyssey gotta fix

So it's not my fault. Great!

**Comment by Midou36O** [comment]
image

for some reason it works for me

**Comment by akisblack** [comment]
i guess odyssey fixed it faster than usual lmao

**Review by Midou36O — APPROVED** [review]
LGTM and works on my end.

**Comment by Odyssey346** [comment]
> i guess odyssey fixed it faster than usual lmao

screw you too. I'll revert it real quick.

**Comment by Midou36O** [comment]
> i guess odyssey fixed it faster than usual lmao

yes, it works on projectsegfau.lt too

**Comment by Midou36O** [comment]
And with this merged you can completely ditch woodpecker but i'd prefer not sending credentials to github, like how travis CI exposed people's secret in a security breach

**Comment by Midou36O** [comment]
For auto updating we will base off watchtower auto update mechanism, sounds good?

**Comment by Odyssey346** [comment]
whatever, man....Sendt fra min Galaxy

**Comment by Midou36O** [comment]
Shut up you didn't even bother helping us

**Comment by Odyssey346** [comment]
help deez nutsSendt fra min Galaxy

**Pull request merged**
